parameters:
    mango_sylius_gpwebpay_payment_gateway_plugin_payment_methods:
        CRD: 'Card Payment'
        MCM: 'MasterCard Mobile'
        MPS: 'MasterPass'
        GPAY: 'Google Pay'
        APAY: 'Apple Pay'
        BTNCS: 'Platba 24'
        BTN360CS: 'Wire Transfer'

services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    MangoSylius\SyliusGPWebpayPaymentGatewayPlugin\Api\GPWebpayApi:
        arguments:
            $translator: '@translator'
            $shopperContext: '@sylius.context.shopper'
            $requestStack: '@request_stack'
            $logger: '@sylius_fixtures.logger'

    mango_sylius:gpwebpay-payment-gateway-plugin:gpwebpay_gateway_factory:
        public: true
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments:
            $gatewayFactoryClass: MangoSylius\SyliusGPWebpayPaymentGatewayPlugin\GPWebpayGatewayFactory
        tags:
            - name: payum.gateway_factory_builder
              factory: gpwebpay

    MangoSylius\SyliusGPWebpayPaymentGatewayPlugin\Form\Type\GPWebpayGatewayConfigurationType:
        arguments:
            $choices: '%mango_sylius_gpwebpay_payment_gateway_plugin_payment_methods%'
        tags:
            - name: sylius.gateway_configuration_type
              type: gpwebpay
              label: mango-sylius.gpwebpay_plugin.gpwebpay
            - name: form.type

    MangoSylius\SyliusGPWebpayPaymentGatewayPlugin\Action\GPWebpayAction:
        public: true
        arguments:
            $gpWebPayApi: '@MangoSylius\SyliusGPWebpayPaymentGatewayPlugin\Api\GPWebpayApi'
        tags:
            - name: payum.action
              factory: gpwebpay
              alias: payum.action.set_gpwebpay

