sylius_twig_hooks:
    hooks:
        'sylius_admin.payment_method.create.content.form.sections.gateway_configuration.gpwebpay':
            form:
                template: '@ThreeBRSSyliusGPWebpayPaymentGatewayPlugin/admin/payment_method/form/form.html.twig'
                priority: 0

        'sylius_admin.payment_method.update.content.form.sections.gateway_configuration.gpwebpay':
            form:
                template: '@ThreeBRSSyliusGPWebpayPaymentGatewayPlugin/admin/payment_method/form/form.html.twig'
                priority: 0
